### PR TITLE
Always pass `--force-update` when adding helm repositories managed by this plugin

### LINKED ISSUE #84: Allow for multiple package executions
If a project has multiple submodules that run `helm:package`, build pipelines will fail with recent versions of Helm (>= v3.3.2) because of a breaking change in the way how `helm repo add` behaves.

Before the change, it was acceptable to add a repository with the same name multiple times and after the change, this is no longer possible.

### LINKED ISSUE #94: Make sure `chartRepo` does not exist before executing helm repo add
When the previous build was interrupted for some reason, a repository named `chartRepo` can continue to stick around.

This prevents future runs of the helm-maven-plugin by causing the following error:

```
[ERROR] Output: Error: repository name (chartRepo) already exists, please specify a different name
[…]
[ERROR] Failed to execute goal com.deviceinsight.helm:helm-maven-plugin:2.8.1:package (default) on project project-name: Error creating helm chart: When executing '/home/walsermi/.m2/repository/com/deviceinsight/helm/helm/3.4.2/helm-3.4.2-linux-amd64.binary repo add chartRepo https://repo-url/ --username xxx --password yyy' got result code '1' -> [Help 1]
```

Ideally the helm-maven-plugin should detect such a situation and perform a clean-up operation.

### PR DESCRIPTION
**Pull request by mwalser**
When Helm 3 is detected, `--force-update` is always passed to `helm repo add`. This restores the behavior that Helm 2 had.

Also, clean up `executeCmd()` a bit. This makes it easier to pass optional arguments and also prevents the smuggling of arguments via the repo URLs.

Closes #94, Closes #84

### CODE REVIEW

File: src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt [hunk 1]
```diff
@@ -38,17 +38,20 @@ abstract class AbstractHelmMojo : AbstractMojo() {
 	@Parameter(property = "chartName", required = false)
 	private var chartName: String? = null
 
-	protected fun executeCmd(cmd: String, directory: File = target(),
-							 redirectOutput: ProcessBuilder.Redirect = ProcessBuilder.Redirect.PIPE) {
-		val proc = ProcessBuilder(cmd.split(" "))
+	protected fun executeCmd(
+		vararg cmd: String,
```
Comment (hho) [inline src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt:42]: Why not take a `List` directly? You're doing `toList` everywhere you use it anyway (except in line 59 – but that one you probably just forgot).

It would also make the spread operator in the TemplateMojo below not needed anymore and would get this function in line with its duplicate still hanging around in the LintMojo…

File: src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt [hunk 2]
```diff
@@ -95,11 +96,13 @@ class PackageMojo : ResolveHelmMojo(), ServerAuthentication {
 
 			processHelmConfigFiles(targetHelmDir)
 
-			if (majorHelmVersion() < 3) {
-				executeCmd("$helm init --client-only --stable-repo-url $stableRepoUrl")
+			val helmAddFlags = if (isHelm2) emptyArray() else arrayOf("--force-update")
```
Comment (hho) [inline src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt:99]: Not sure about this one – it's potentially destructive, so we either have to make it a major release (breaking change) with very clear documentation about this, or we make it a parameter, so people have to opt-in to the new behavior.

File: src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt (hunk 1 above)
Comment (mwalser) [reply src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt]: I thought that the command is more ergonomic to use with varargs, but I don't have any strong feelings on this so I switched it over to using a List

File: src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt (hunk 2 above)
Comment (mwalser) [reply src/main/kotlin/com/deviceinsight/helm/PackageMojo.kt]: Yeah, you are right. I've introduced the `forceAddRepos` flag which defaults to `false`

File: src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt [hunk 3]
```diff
@@ -39,24 +40,32 @@ abstract class AbstractHelmMojo : AbstractMojo() {
...
 			.redirectOutput(redirectOutput)
 			.redirectError(ProcessBuilder.Redirect.PIPE)
 			.start()
 
+		val stdoutPrinter = thread(name = "Stdout printer") {
+			proc.inputStream.bufferedReader().lines().forEach { log.debug("Output: $it") }
+		}
+
+		val stderrPrinter = thread(name = "Stderr printer") {
+			proc.errorStream.bufferedReader().lines().forEach { log.error("Output: $it") }
```
Comment (mwalser) [inline src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt:58]: I hope you don't mind me spawning two threads only for printing out the stdout/stderr stream

**Review by hho — CHANGES_REQUESTED** [review]

File: src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt [hunk 4]
```diff
@@ -38,22 +39,33 @@ abstract class AbstractHelmMojo : AbstractMojo() {
...
+		redirectOutput: ProcessBuilder.Redirect = ProcessBuilder.Redirect.PIPE
+	) {
+		val proc = ProcessBuilder(cmd)
 			.directory(directory)
 			.redirectOutput(redirectOutput)
 			.redirectError(ProcessBuilder.Redirect.PIPE)
 			.start()
 
+		val stdoutPrinter = thread(name = "Stdout printer") {
+			proc.inputStream.bufferedReader().lines().forEach { log.debug("Output: $it") }
```
[the remark this answers is not in the document]
Comment (mwalser) [reply src/main/kotlin/com/deviceinsight/helm/AbstractHelmMojo.kt]: Good catch. I didn't see that lint was logging to info. I guess thats the problem with having two methods that are doing roughly the same but slightly different.

I added an option to `executeCmd` for logging to `info` instead of `debug`. Also I hope it's ok if I still spawn a thread for logging stdout even when it is redirected to a file. This keeps the code a bit less noisy.

This will still work:
> If the standard output of the process has been redirected using ProcessBuilder.redirectOutput then this method will return a null input stream.

File: CHANGELOG.adoc [hunk 5]
```diff
@@ -3,6 +3,7 @@
 == Unreleased
 
 * Support authentication to the helm repository using credentials from server definitions in maven `settings.xml` via `chartRepoServerId`.
+* Always pass `--force-update` when adding helm repositories managed by this plugin.
```
[the remark this answers is not in the document]
Comment (mwalser) [reply CHANGELOG.adoc]: I've updated the wording

**Review by hho — APPROVED** [review]
LGTM
